version: '3'

services:
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on: 
      - app

  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: /bin/bash -c 'wait-for-it --timeout=30 db:3306 -- npm install && npm install faker && npm audit fix --force && node index.js'
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    
  db:
    platform: linux/amd64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  
networks:
  node-network:
    driver: bridge