version: '3'

services:
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on: 
      - app

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on: 
      - db    
    networks:
      - node-network

  db:
    image: mysql:5.7              
    container_name: db 
    command: --innodb-use-native-aio=0    
    restart: always
    tty: true
    
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password    
    networks:
      - node-network  

networks:
  node-network:
    driver: bridge